//
//  SEBBrowserControllerTrustTests.swift
//  SafeExamBrowserTests
//
//  Regression tests for the server-trust authorization decision in
//  +[SEBBrowserController shouldAuthorizeServerTrust:...], guarding the removed
//  authorizedHosts substring bypass (CWE-295): a previously successful trust
//  evaluation must NEVER authorize a later failed evaluation, regardless of any
//  host relationship (same host, subdomain, non-label substring, attacker suffix)
//  and regardless of pinEmbeddedCertificates.
//
//  The certificates are fixtures generated by scripts/gen-trust-test-fixtures.sh
//  (a test CA plus leaves). Leaves carry EKU serverAuth + a SAN and are valid for
//  397 days (<= Apple's 398-day TLS limit); only the root CA is long-lived. The
//  "expired" leaf is intentionally expired. Regenerate with the script if they age
//  out (~2027-09), pasting the new base64 over the constants below.
//
//  Uses XCTest to match the other unit tests in this target.
//

import XCTest
import Safe_Exam_Browser

final class SEBBrowserControllerTrustTests: XCTestCase {

    // MARK: - Fixtures (base64 DER, see scripts/gen-trust-test-fixtures.sh)

    // Test root CA (self-signed, CA:TRUE).
    private let caB64 = "MIIDKTCCAhGgAwIBAgIUI1CWhqmCKH2m0GjoVIukr/xIJTQwDQYJKoZIhvcNAQELBQAwGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTAgFw0yNjA4MDUxNjQ2MjBaGA8yMTI2MDcxMjE2NDYyMFowGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANv8IKs+MjYn3CHAbQFhWOBXene+0+L85oMtrQaUawqraofX/Dr5n3jMKz3UHpf8RkokukTPd3kyViO4Tjo4OBQmNRC2M781l8GHBqUP07ILAdlsqilWmWeDo3t/+g8N7w2uwEe4kO+gU3bjucUJ5t9uMOYlzD8+yF5mAA8GHqcOSmcEwkurq6T3v/VRrbOxgXCE/PhJN1SXtJTxTrehoB/fi1t0cmaWJu3BfkB3+UnAvh5lJ/Q04fbJsdY3xkLMq0KckzDdm4keHw3/HkZqICM9ndnwI8lClo0D5Tr5ij4fa3DKZCBUBwwhFrsx/4TG7YFac8+eCRTxCsnEC9loCZkCAwEAAaNjMGEwHQYDVR0OBBYEFPprJKQKkH2q4udv4H3YHeMx2vbQMB8GA1UdIwQYMBaAFPprJKQKkH2q4udv4H3YHeMx2vbQMA8GA1UdEwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQCporaFZFdGHZkSXDVs/Zol2X4SXfhzLNrqWjBbrn9V/WZH6/GQTAwDXoshjCR3Qx7KCt4E2V2tEN0T6bGzeiJ3ZItdpDUDeEQ86mHuLe9MUFY1rqmvz4YD5tQ8x2+YniQCa8YlihgCFOQ966Klyg8KtowCNw1ahLgVxwY5W3j3rZDYMnPdkAy7seHzGqqedYR56YXSxdECSzSUHyrUSz4XuXtqN6ulMRWPseCbmgGSN+ctoYQbTPogohIDLxPE+luxd5miZo96IpyK0PB3baaJ9jvnjG+Y5NOptsqitLIjNHjP1ON8oFzf7wgsVHndfR6s4+jt8BVZg68bFrQzl5GG"

    // Valid leaf for example.test, chaining to the test CA.
    private let validExampleB64 = "MIIDUDCCAjigAwIBAgIUZi5z/GWnTANAHDKJa5mlOHM/DEEwDQYJKoZIhvcNAQELBQAwGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTAeFw0yNjA4MDUxNjQ2MjFaFw0yNzA5MDYxNjQ2MjFaMBcxFTATBgNVBAMMDGV4YW1wbGUudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANhrAMn5mMrfOlRnfPNVH2fVMf8zhD15FaR1YSGzY93+FzlmtBVuJtjfj1qY9rzB5kniMPTqDjJ5AlgaXDbyI08EYpGEXoAaoEPWNMHVtZbJqBOAWLNaR8W2p82jJ2H1r4I4MXhhY52UIUMBKKjAEM0aY3LCPZD5W43Mh/1upOOxByZkkNgAvors5hDePXK2L85paKGwGLqbG2JPW8l/3SIs0NEdOeJCNXjZTZbfyjsYLt0WgApp0FnOruxGK/Nt014hccmSCt/S+FmNAuDvZH+FPjWlFuUeu77UrHQmw0tCpOdt/9Mx0XDaowK42OY4wkWcnLU88RayPrHNkZVXTMMCAwEAAaOBjzCBjDAXBgNVHREEEDAOggxleGFtcGxlLnRlc3QwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYEFJP5uWbrjy3iZlOH/huGCQeODNTJMB8GA1UdIwQYMBaAFPprJKQKkH2q4udv4H3YHeMx2vbQMA0GCSqGSIb3DQEBCwUAA4IBAQBe/+0rYrk7eZ/soZ8Pib+wZRe1T3B7vTxjS31zd3OS1k/uVFi+bGguF6z/1NnqHLD7uvRl2NXvf4wAZELVb2IR7cSq2VbF94C+ZLdWukJ2UI0XtJDFbL/KP8cHHy3tEWjwR1iB21cbauUBy4cZ1yRwU5zlOwqO7nAazobYMZjtX/22fQ80nCcqstHP4oqyGUnRBDLMYWmk9uN5Yyq6tqgXgXXm+sndgRU4ytO3PJwZ+hcBdNTS994vrzCqgXBl99LNwcB2rFrZsmXWBaZ82OIUVlp1U7SAulFtvQQWPPncoZfgy7nOVF0XaRwaGs8oqHgGgmjMupr6wNqGcuplMZIy"

    // Valid leaf for sub.example.test, chaining to the test CA.
    private let validSubB64 = "MIIDWDCCAkCgAwIBAgIUZi5z/GWnTANAHDKJa5mlOHM/DEIwDQYJKoZIhvcNAQELBQAwGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTAeFw0yNjA4MDUxNjQ2MjFaFw0yNzA5MDYxNjQ2MjFaMBsxGTAXBgNVBAMMEHN1Yi5leGFtcGxlLnRlc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCs3kU11YnW1g0aahpewZf31SAcH7Wo63w+kYffzWwRkCXHMRqiuXQRizPwgWe/NKuD9FPglQrcuZrbp7Rq+00YXZdhuhDs+p5LmZI3VSfjw97HGXG1OBXlkYN4rO2JMvVRLmyfTyyeMPXLDL02VBhSD5owz5ftBl7Ju1mzuQXR2pix88ZwOj81/xBvwR3Kzro6O6eKKEbjAQYQtPfbHHFTRO6SQh9FYb/zIKvequmhPwNO8tCMvJefKF6oJtvoGsWMZTH1tcfvvBj/RrJV+BYDXnXDq3whSZo+ZKeHa1swIM3smJ8aTexNgGChfaOmRA3TXv3p4xntAXrxKrRea3/BAgMBAAGjgZMwgZAwGwYDVR0RBBQwEoIQc3ViLmV4YW1wbGUudGVzdDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAdBgNVHQ4EFgQURQYp2T/DvcRP9HLtNoFnm2ORipUwHwYDVR0jBBgwFoAU+mskpAqQfari52/gfdgd4zHa9tAwDQYJKoZIhvcNAQELBQADggEBALoc1nVGSRXVrIq/Vm6IlYjwy6b1Kgy/SXEuNd2+0lOsJBV1PbEul8DpTUr+4SEovBl9ezu8c1RI7SFCUGesJFbfE802EHy5jt0C2rzzsVsf49h4h5WXq7fANa5X2r3fpOgmXWTuKDGNVEAEsizNBdmIokcWxNSO1nOgsovvh2ZeAU3kVHGLOceBXfPtoCMIlUHbHyqv15QBpJIhwx7DIAuxS/En77LYSc2HQz9euwNkzYqYcxdp8V+sEaHcB++iU89jlpfRX4hMwgHgvAgIgEj9CMH873oxy3UaXOc90m0ti10lUSEX0XkGL3mpa7Vx9tGNK9GiQG+i+ao4lUosEgg="

    // CA-signed leaf whose only SAN is other.test (wrong host for example.test).
    private let wrongHostB64 = "MIIDTDCCAjSgAwIBAgIUZi5z/GWnTANAHDKJa5mlOHM/DEMwDQYJKoZIhvcNAQELBQAwGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTAeFw0yNjA4MDUxNjQ2MjFaFw0yNzA5MDYxNjQ2MjFaMBUxEzARBgNVBAMMCm90aGVyLnRlc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCO8IAAO9EnE98Llne4c8/V04FsLGamtBEC7lv7nk6kwZg8m0MxOlPAiBgXVM1Zu06LqbuZvFXeZvz3WhcAulbGaEonrSXNOWgJAgqr1Zkd6jti5/cnqhKkjXvOjGWtmkeoEs6qIPHbIuj/jxdJyDbQy9k3FFJRu0iW+/z99WpR69VkUBasOkwu/R/Ia7f0s+HlCKbYdDcr1DcPVH0xASJDzleqj9XPF+KLdVZpJbZExWhx4Ci3UgTB/CjhtvUzd+NqzyLJC9+xpHCj7GbKdmkd+YFd9/YlAQ/81zX+EJCgid9Wstiv+XvA3iqoGBj6ATaJDKRvjVU0kEVjJDIbjmghAgMBAAGjgY0wgYowFQYDVR0RBA4wDIIKb3RoZXIudGVzdDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAdBgNVHQ4EFgQUO7jjIJcuGbwqM9ng5V02EkGDjlEwHwYDVR0jBBgwFoAU+mskpAqQfari52/gfdgd4zHa9tAwDQYJKoZIhvcNAQELBQADggEBAFHFJuTjWvvhjzOo8ey5Xn4uQZbP+tH6WcoijJHii0P25O8+NX8dC7sXvSc6mCjsLuEth0hZMkrX+x4b9jMw6eXqNAqCcjZgnjfEygjFZovXAfWLPBtQFCGcsjsnmDl/rk0qasQuj5fiNeRIK77qZGfqizCFnLpoqtf3NviAaT0g0em4+9PTer65lPiyReTppUw4aOZy3T5W+xMnJTaGv8H3u8YcoYc3pA+p6WRvuprevt9ybQqLpMbAQhZEmdov/ErgdUO/69oxZ+OyzXEnisUOpJ9z7XaFgl3PkqBfNd30OJ5XpCh99JA6dfqvxO+cPOrPV1N41jvKn5hEPrfMHjw="

    // CA-signed leaf for example.test, but valid only 2000..2001 (expired).
    private let expiredB64 = "MIIDUDCCAjigAwIBAgIURQMdkhmNp5NwMus0e06k8z++3IMwDQYJKoZIhvcNAQELBQAwGzEZMBcGA1UEAwwQU0VCIFRlc3QgUm9vdCBDQTAeFw0wMDAxMDEwMDAwMDBaFw0wMTAxMDEwMDAwMDBaMBcxFTATBgNVBAMMDGV4YW1wbGUudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAIyZKOE0zANdjF6W6Sjv9/TwUqah3NvrsshHsghu+6MCurYH0sTe01h3mMI/c1VCxBpnCfDvpniiKkViuKeMuwpg40qb1sUErUgwu+Wnqabv3iJsJ+jzac1RxcjLtrhaf/FbIYJWTGhn2FSjQCSq5TxIfoch5VQ00ntIdEWg5KOvG+T2Jhsgmql9O9tFIqIGlwn/EXDBktN7Vwq8y2zC3hV1bIgxgR+8VprMeZryMRZr+MwqJOKZgizpeFK6mYp2mdWAZXVPiNHxBlzcSPQX2vyEW+r3YUWmlYx4hj9FsZL+QtfsDJnXY8u/kFTLVkcXCAVhfg+eY6HcbURzJFPiV6ECAwEAAaOBjzCBjDAXBgNVHREEEDAOggxleGFtcGxlLnRlc3QwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYEFI4c/AuxpA7nPpJ63I5QOLvPqK+DMB8GA1UdIwQYMBaAFPprJKQKkH2q4udv4H3YHeMx2vbQMA0GCSqGSIb3DQEBCwUAA4IBAQBfjNwwEAtt+CfJ5WaFne/VjgBE+qAVe0kIzTge8uCRNcYa7NZEtGMKAJ4UbHD9ly/uVcD0wzEC+Q7Edf0E27zEeqhj0bVaEe2e8VWSqTOiMriKK9BdF/wHWp0L/YEuOR5b9l73/G3N6WbEyv7z6NJxRps2YKATxY/nh8vt4LgxRmSpQzKVdOebXFhbyeFKqoPJFDUzSa1lB19X/Bflsj+QcZYl4Wd7t6HPynAPgipVb6hz7v3KGcAdAac+23v9T2D7BC9t9N3XBOGqDb9Y9QN2grcjlzVyb/TTL/3lecVpVk+oOjmZOPeJoZPd5blKnELBjODp5GMdq1ekrUeMoHVy"

    // Self-signed leaf for example.test (unknown CA).
    private let selfSignedB64 = "MIIDTDCCAjSgAwIBAgIUXMIZNlxE7TfNPtEzxFjRJT2KIeswDQYJKoZIhvcNAQELBQAwFzEVMBMGA1UEAwwMZXhhbXBsZS50ZXN0MB4XDTI2MDgwNTE2NDYyMVoXDTI3MDkwNjE2NDYyMVowFzEVMBMGA1UEAwwMZXhhbXBsZS50ZXN0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmfigdXdntuT38AJdDENnLn6pg+dh/NPHtQsmowbERgkhbIUEJCb4pnUYe6EqgJ3ReaKsKLux2O+sPTrtJmHLM90NjSO7kbsc13aEIZt2ux/v0T3jo7t/cFCE5WCnhU+zsFJExf9Kj6dXzRUvMPcDjdAAefwzib22GBfwUKQXIlREgL5fnaXSHoaN7zuqUEEjHtDFCH1Vvb51yIzooxMS530TTro250RCdS3xtDJ5BSwwK8D7mMRVDPIkYoOWN4U75r68u4y9ryD4h7N3HPwewhRoEnPFXA1NEzaSVnU9cfDreQMRyUU8CKdDLG5YtN94chUdpsFYC1maXgHkF7V2wIDAQABo4GPMIGMMB0GA1UdDgQWBBSVNpcBDlavtIxiL9DG5EHegEElwjAfBgNVHSMEGDAWgBSVNpcBDlavtIxiL9DG5EHegEElwjAXBgNVHREEEDAOggxleGFtcGxlLnRlc3QwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBACOWNL1V7dq2uwwoZf5y1GsifJ7RaqY0TtRee/b1wYasHRlpoYgeFY/J29KhlrKjIu1NyECD4LQQ1MNfpOA1upANr3jgdqDQsqL+5IMoGC0Jk+twQOm0Q2pRMaK53S7mQr+EwNGoNpULUft4Z3J5qK6+Kw60jAXKaaKyt89oITBp7kodns+h3NqvDilskPZuJRQ6KyhsMYkWgPVl7XhUwKxVeZMDlF50Klq27wcgC6CgQb3ltByn3Cn8LsrrQ7zg4iXoUqE+wYWHCk2psEmqI/OPxlcdutb6qBwT4Bmr3WPNlwo5KwA8Ru2CjlIQSTzXC/1z+Ebittoe60ismazFx94="

    // MARK: - Helpers

    private func der(_ b64: String, _ file: StaticString = #filePath, _ line: UInt = #line) -> Data {
        guard let data = Data(base64Encoded: b64) else {
            XCTFail("Invalid base64 fixture", file: file, line: line)
            return Data()
        }
        return data
    }

    /// Runs the production decision. `caCerts`/`tlsCerts`/`debugCerts` default to empty.
    private func authorize(leaf: String,
                           host: String,
                           port: Int = 443,
                           caCerts: [String] = [],
                           tlsCerts: [String] = [],
                           debugCerts: [String] = [],
                           debugCertNames: [String] = [],
                           pinEmbedded: Bool) -> Bool {
        SEBBrowserControllerTrustTestSupport.authorizeServerPresentingLeaf(
            der(leaf),
            host: host,
            port: port,
            caCertsDER: caCerts.map { der($0) },
            tlsCertsDER: tlsCerts.map { der($0) },
            debugCertsDER: debugCerts.map { der($0) },
            debugCertNames: debugCertNames,
            pinEmbeddedCertificates: pinEmbedded)
    }

    // MARK: - Legitimate accept paths (must keep working)

    // Valid leaf chaining to the embedded CA, not pinned.
    func testValidCertChainingToEmbeddedCA_isAuthorized() {
        for pin in [false, true] {
            XCTAssertTrue(authorize(leaf: validExampleB64, host: "example.test",
                                    caCerts: [caB64], pinEmbedded: pin),
                          "valid CA-chained cert must be authorized (pin=\(pin))")
        }
    }

    // A valid subdomain leaf chaining to the embedded CA.
    func testValidSubdomainCert_isAuthorized() {
        XCTAssertTrue(authorize(leaf: validSubB64, host: "sub.example.test",
                                caCerts: [caB64], pinEmbedded: false))
    }

    // Exact public-key pin of a self-signed cert.
    func testExactPublicKeyPin_isAuthorized() {
        XCTAssertTrue(authorize(leaf: selfSignedB64, host: "example.test",
                                tlsCerts: [selfSignedB64], pinEmbedded: true),
                      "server cert whose public key is pinned must be authorized")
    }

    // MARK: - Rejections (independent of any prior success)

    func testUnknownCASelfSigned_isRejected() {
        for pin in [false, true] {
            XCTAssertFalse(authorize(leaf: selfSignedB64, host: "example.test",
                                     caCerts: [caB64], pinEmbedded: pin),
                           "self-signed (unknown CA) cert must be rejected (pin=\(pin))")
        }
    }

    func testExpiredCert_isRejected() {
        for pin in [false, true] {
            XCTAssertFalse(authorize(leaf: expiredB64, host: "example.test",
                                     caCerts: [caB64], pinEmbedded: pin),
                           "expired cert must be rejected (pin=\(pin))")
        }
    }

    func testHostnameMismatch_isRejected() {
        // CA-signed, but the certificate is for other.test.
        for pin in [false, true] {
            XCTAssertFalse(authorize(leaf: wrongHostB64, host: "example.test",
                                     caCerts: [caB64], pinEmbedded: pin),
                           "wrong-host cert must be rejected (pin=\(pin))")
        }
    }

    func testPinnedButPublicKeyMismatch_isRejected() {
        // Pinning a different cert must not authorize the presented self-signed cert.
        XCTAssertFalse(authorize(leaf: selfSignedB64, host: "example.test",
                                 tlsCerts: [validExampleB64], pinEmbedded: true))
    }

    // MARK: - CWE-295 regression: no cross-connection host fallback

    // The core of the reported vulnerability: after example.test was validated with
    // a good cert, a failing cert for the SAME host must still be rejected. Because
    // the decision is stateless the prior success cannot leak in — assert both.
    func testValidThenInvalidSameHost_secondIsRejected() {
        for pin in [false, true] {
            XCTAssertTrue(authorize(leaf: validExampleB64, host: "example.test",
                                    caCerts: [caB64], pinEmbedded: pin))
            XCTAssertFalse(authorize(leaf: selfSignedB64, host: "example.test",
                                     caCerts: [caB64], pinEmbedded: pin),
                           "a prior success must not authorize a later failed cert for the same host (pin=\(pin))")
        }
    }

    // A failing cert for a real subdomain must be rejected even after the parent
    // domain was validated.
    func testInvalidCertForRealSubdomain_isRejected() {
        XCTAssertTrue(authorize(leaf: validExampleB64, host: "example.test",
                                caCerts: [caB64], pinEmbedded: false))
        // self-signed example.test cert presented for host sub.example.test:
        // unknown CA + hostname mismatch.
        XCTAssertFalse(authorize(leaf: selfSignedB64, host: "sub.example.test",
                                 caCerts: [caB64], pinEmbedded: false))
    }

    // A host containing the trusted host as a NON-LABEL substring (the old predicate
    // matched this). Present the CA-signed example.test cert for notexample.test:
    // chains to the CA but the hostname does not match -> must be rejected.
    func testNonLabelSubstringHost_isRejected() {
        XCTAssertTrue(authorize(leaf: validExampleB64, host: "example.test",
                                caCerts: [caB64], pinEmbedded: false))
        XCTAssertFalse(authorize(leaf: validExampleB64, host: "notexample.test",
                                 caCerts: [caB64], pinEmbedded: false),
                       "hostname mismatch must be rejected even though 'notexample.test' contains 'example.test'")
    }

    // The attacker-suffix case example.test.attacker.test.
    func testAttackerSuffixHost_isRejected() {
        XCTAssertTrue(authorize(leaf: validExampleB64, host: "example.test",
                                caCerts: [caB64], pinEmbedded: false))
        XCTAssertFalse(authorize(leaf: validExampleB64, host: "example.test.attacker.test",
                                 caCerts: [caB64], pinEmbedded: false),
                       "hostname mismatch must be rejected for an attacker suffix domain")
    }
}
